---
version: '3.8'

services:
  oracle:
    image: container-registry.oracle.com/database/express:latest
    hostname: oracle
    container_name: oracle
    ports:
      - 1521:1521
      - 5500:5500
    environment:
      ORACLE_PWD: testing
    volumes:
      - ./oradata:/opt/oracle/oradata
      - ./orasetup:/opt/oracle/scripts/setup