---
version: '3.8'

services:
  wildfly:
    image: quay.io/wildfly/wildfly:26.0.1.Final
    hostname: wildfly
    container_name: wildfly
    ports:
      - 8080:8080
      - 9990:9990
    entrypoint: '/docker-entrypoint.sh'
    environment:
      CDN_HOSTNAME: 'localhost'
    volumes:
      - ./docker/wildfly/docker-entrypoint.sh:/docker-entrypoint.sh
      - ./docker/wildfly/TestOracleConnection.java:/TestOracleConnection.java
      - ./docker/wildfly/standalone.xml:/opt/jboss/wildfly/standalone/configuration/standalone.xml
      - ./docker/wildfly/module.xml:/opt/jboss/wildfly/modules/com/oracle/database/jdbc/main/module.xml
      - ./build/ojdbc11-21.3.0.0.jar:/opt/jboss/wildfly/modules/com/oracle/database/jdbc/main/ojdbc11-21.3.0.0.jar
      - ./build/libs/:/opt/jboss/wildfly/standalone/deployments/