services:
  oracle:
    extends:
      file: deps.yml
      service: oracle

  keycloak:
    extends:
      file: deps.yml
      service: keycloak

  puppet:
    extends:
      file: deps.yml
      service: puppet

  mailhog:
    extends:
      file: deps.yml
      service: mailhog

  bam:
    hostname: bam
    container_name: bam
    ports:
      - "8443:8443"
      - "8080:8080"
      - "9990:9990"
    environment:
      BAM_FEEDBACK_SENDER_ADDRESS: 'admin@example.com'
      BAM_FEEDBACK_TO_ADDRESS_CSV: 'user1@example.com,user2@example.com'
      BAM_CONTENT_CONTACT: 'bob@example.com'
      BAM_TECHNICAL_CONTACT: 'larry@example.com'
      BAM_DOC_CSV: 'https://github.com/JeffersonLab/bam|BAM Home,https://jlab.org|JLAB Home'
      BAM_BOOKS_CSV: TLOG
      BAM_PERMISSIONS_EMAIL_CSV: permission-recipient1@example.com,permission-recipient2@example.com
      BAM_UPCOMING_EXPIRATION_EMAIL_CSV: upcoming-recipient@example.com,upcoming-recipient2@example.com
      BAM_EXPIRED_EMAIL_CSV: expired-recipient1@example.com,expired-recipient2@example.com
      BAM_DOWNGRADED_EMAIL_CSV: downgrade-recipient1@example.com,downgrade-recipient2@example.com
      BAM_PERMISSIONS_SUBJECT: '[TESTING] Beam Authorization Updated'
      BAM_UPCOMING_EXPIRATION_SUBJECT: '[TESTING] Beam Authorization Expired / Expiring Soon'
      BAM_EXPIRED_SUBJECT: '[TESTING] Beam Authorization Expired'
      BAM_DOWNGRADED_SUBJECT: '[TESTING] Beam Authorization Downgraded'
      BAM_EMAIL_SENDER: 'bam@example.com'
      KEYCLOAK_REALM: 'test-realm'
      KEYCLOAK_RESOURCE: 'bam'
      KEYCLOAK_SECRET: 'yHi6W2raPmLvPXoxqMA7VWbLAA2WN0eB'
      KEYCLOAK_SERVER_URL: 'http://keycloak:8080'
      LOGBOOK_SERVER: 'elog'
      ORACLE_DATASOURCE: 'bam'
      ORACLE_SERVER: 'oracle:1521'
      ORACLE_USER: 'BAM_OWNER'
      ORACLE_PASS: 'password'
      ORACLE_SERVICE: 'xepdb1'
      PUPPET_SHOW_SERVER: 'puppet:3000'
      PROXY_SERVER: 'localhost:8443'
      TZ: 'America/New_York'