---
version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:16.1.1
    hostname: keycloak
    container_name: keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
