---
version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:16.1.1
    hostname: keycloak
    container_name: keycloak
    ports:
      - "8081:8080"
      - "9991:9990"
    environment:
      DB_VENDOR: h2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /realm.json
    volumes:
      - ./docker/keycloak/realm.json:/realm.json
      - ./docker/keycloak/setup.sh:/opt/jboss/startup-scripts/setup.sh
