
CREATE TABLESPACE BEAM_AUTH;

CREATE USER "BEAM_AUTH_OWNER" PROFILE "DEFAULT" IDENTIFIED BY "password" DEFAULT TABLESPACE "BEAM_AUTH" ACCOUNT UNLOCK;

grant connect to BEAM_AUTH_OWNER;
grant create view to BEAM_AUTH_OWNER;
grant create sequence to BEAM_AUTH_OWNER;
grant create table to BEAM_AUTH_OWNER;
grant unlimited tablespace to BEAM_AUTH_OWNER; 
grant create procedure to BEAM_AUTH_OWNER;
grant create type to BEAM_AUTH_OWNER;

DROP SEQUENCE AUTHORIZATION_ID;

CREATE SEQUENCE AUTHORIZATION_ID;

DROP SEQUENCE CONTROL_VERIFICATION_ID;

CREATE SEQUENCE CONTROL_VERIFICATION_ID;

DROP SEQUENCE VERIFICATION_HISTORY_ID;

CREATE SEQUENCE VERIFICATION_HISTORY_ID;

DROP TABLE VERIFICATION_HISTORY CASCADE CONSTRAINTS PURGE;

DROP TABLE CONTROL_VERIFICATION CASCADE CONSTRAINTS PURGE;

DROP TABLE VERIFICATION CASCADE CONSTRAINTS PURGE;

DROP TABLE CREDITED_CONTROL CASCADE CONSTRAINTS PURGE;

DROP TABLE DESTINATION_AUTHORIZATION CASCADE CONSTRAINTS PURGE;

DROP TABLE AUTHORIZATION CASCADE CONSTRAINTS PURGE;

DROP TABLE BEAM_AUTH_DESTINATION CASCADE CONSTRAINTS PURGE;

DROP TABLE BEAM_AUTH_SETTINGS CASCADE CONSTRAINTS PURGE;

CREATE TABLE BEAM_AUTH_SETTINGS
(
	BEAM_AUTH_SETTINGS_ID INTEGER NOT NULL ,
	DOWNGRADE_EMAIL_ADDRESSES VARCHAR2(1048 CHAR) NULL ,
CONSTRAINT  BEAM_AUTH_SETTINGS_PK PRIMARY KEY (BEAM_AUTH_SETTINGS_ID)
);

CREATE TABLE BEAM_AUTH_DESTINATION
(
	BEAM_DESTINATION_ID  INTEGER NOT NULL ,
	MACHINE              VARCHAR2(32 CHAR) DEFAULT  'CEBAF'  NOT NULL ,
	CURRENT_LIMIT_UNITS  VARCHAR2(3 CHAR) DEFAULT  'uA'  NOT NULL ,
	DISPLAY_NAME         VARCHAR2(32 CHAR) NULL ,
	ACTIVE_YN            CHAR(1 BYTE) DEFAULT  'Y'  NOT NULL  CONSTRAINT  BEAM_AUTH_DESTINATIONS_CK1 CHECK (ACTIVE_YN IN ('Y', 'N')),
CONSTRAINT  BEAM_AUTH_DESTINATIONS_PK PRIMARY KEY (BEAM_DESTINATION_ID)
);

CREATE TABLE AUTHORIZATION
(
	AUTHORIZATION_ID     INTEGER NOT NULL ,
	MODIFIED_DATE        DATE NOT NULL ,
	MODIFIED_BY          INTEGER NOT NULL ,
	AUTHORIZATION_DATE   DATE NOT NULL ,
	AUTHORIZED_BY        INTEGER NOT NULL ,
	COMMENTS             VARCHAR2(2048 CHAR) NULL ,
CONSTRAINT  AUTHORIZATION_PK PRIMARY KEY (AUTHORIZATION_ID)
);

CREATE TABLE DESTINATION_AUTHORIZATION
(
	BEAM_DESTINATION_ID  INTEGER NOT NULL ,
	AUTHORIZATION_ID     INTEGER NOT NULL ,
	BEAM_MODE            VARCHAR2(16) NOT NULL  CONSTRAINT  DESTINATION_AUTHORIZATION_CK1 CHECK (BEAM_MODE IN ('Tune', 'CW', 'None')),
	CW_LIMIT             NUMBER(24,12) NULL ,
	COMMENTS             VARCHAR2(256) NULL ,
	EXPIRATION_DATE      DATE NULL ,
CONSTRAINT  DESTINATION_AUTHORIZATION_PK PRIMARY KEY (BEAM_DESTINATION_ID,AUTHORIZATION_ID),
CONSTRAINT DESTINATION_AUTHORIZATION_FK1 FOREIGN KEY (AUTHORIZATION_ID) REFERENCES AUTHORIZATION (AUTHORIZATION_ID)
);

CREATE TABLE CREDITED_CONTROL
(
	CREDITED_CONTROL_ID  INTEGER NOT NULL ,
	NAME                 VARCHAR2(128 CHAR) NOT NULL ,
	DESCRIPTION          VARCHAR2(2048 CHAR) NULL ,
	GROUP_ID             INTEGER NOT NULL ,
	WEIGHT               INTEGER NULL ,
	VERIFICATION_FREQUENCY VARCHAR2(128 CHAR) NULL ,
	COMMENTS             VARCHAR2(2048) NULL ,
CONSTRAINT  CREDITED_CONTROL_PK PRIMARY KEY (CREDITED_CONTROL_ID)
);

CREATE TABLE VERIFICATION
(
	VERIFICATION_ID      SMALLINT NOT NULL ,
	NAME                 VARCHAR2(128 CHAR) NOT NULL ,
CONSTRAINT  VERIFICATION_PK PRIMARY KEY (VERIFICATION_ID)
);

CREATE TABLE CONTROL_VERIFICATION
(
	CONTROL_VERIFICATION_ID INTEGER NOT NULL ,
	CREDITED_CONTROL_ID  INTEGER NULL ,
	BEAM_DESTINATION_ID  INTEGER NOT NULL ,
	VERIFICATION_ID      SMALLINT DEFAULT  'N'  NOT NULL  CONSTRAINT  CONTROL_VERIFICATION_CK1 CHECK (VERIFICATION_ID IN ('Y', 'N')),
	VERIFICATION_DATE    DATE NULL ,
	VERIFIED_BY          INTEGER NULL ,
	EXPIRATION_DATE      DATE NULL ,
	COMMENTS             VARCHAR2(2048 CHAR) NULL ,
	MODIFIED_BY          INTEGER NOT NULL ,
	MODIFIED_DATE        DATE NOT NULL ,
CONSTRAINT  CONTROL_VERIFICATION_PK PRIMARY KEY (CONTROL_VERIFICATION_ID),CONSTRAINT  CONTROL_VERIFICATION_AK1 UNIQUE (CREDITED_CONTROL_ID,BEAM_DESTINATION_ID),
CONSTRAINT CONTROL_VERIFICATION_FK1 FOREIGN KEY (CREDITED_CONTROL_ID) REFERENCES CREDITED_CONTROL (CREDITED_CONTROL_ID) ON DELETE CASCADE,
CONSTRAINT CONTROL_VERIFICATION_FK3 FOREIGN KEY (VERIFICATION_ID) REFERENCES VERIFICATION (VERIFICATION_ID) ON DELETE SET NULL
);

CREATE TABLE VERIFICATION_HISTORY
(
	VERIFICATION_HISTORY_ID INTEGER NOT NULL ,
	CONTROL_VERIFICATION_ID INTEGER NOT NULL ,
	VERIFICATION_ID      SMALLINT NOT NULL ,
	VERIFIED_BY          INTEGER NULL ,
	VERIFICATION_DATE    DATE NOT NULL ,
	EXPIRATION_DATE      DATE NULL ,
	COMMENTS             VARCHAR2(2048 CHAR) NULL ,
	MODIFIED_BY          INTEGER NOT NULL ,
	MODIFIED_DATE        DATE NOT NULL ,
CONSTRAINT  VERIFICATION_HISTORY_PK PRIMARY KEY (VERIFICATION_HISTORY_ID),
CONSTRAINT VERIFICATION_HISTORY_FK1 FOREIGN KEY (CONTROL_VERIFICATION_ID) REFERENCES CONTROL_VERIFICATION (CONTROL_VERIFICATION_ID) ON DELETE CASCADE,
CONSTRAINT VERIFICATION_HISTORY_FK3 FOREIGN KEY (VERIFICATION_ID) REFERENCES VERIFICATION (VERIFICATION_ID) ON DELETE SET NULL
);

ALTER TABLE CONTROL_VERIFICATION ADD CONSTRAINT CONTROL_VERIFICATION_FK2 FOREIGN KEY (BEAM_DESTINATION_ID) REFERENCES hco_owner.BEAM_DESTINATION (BEAM_DESTINATION_ID) ON DELETE SET NULL;

--ALTER TABLE CREDITED_CONTROL ADD CONSTRAINT CREDITED_CONTROL_FK1 FOREIGN KEY (WORKGROUP_ID) REFERENCES WORKGROUP (WORKGROUP_ID) ON DELETE SET NULL;

ALTER TABLE DESTINATION_AUTHORIZATION ADD CONSTRAINT DESTINATION_AUTHORIZATION_FK2 FOREIGN KEY (BEAM_DESTINATION_ID) REFERENCES hco_owner.BEAM_DESTINATION (BEAM_DESTINATION_ID) ON DELETE SET NULL;

--ALTER TABLE CREDITED_CONTROL ADD CONSTRAINT CREDITED_CONTROL_FK3 FOREIGN KEY (STAFF_ID) REFERENCES STAFF (STAFF_ID) ON DELETE SET NULL;

--ALTER TABLE CERTIFICATION_HISTORY ADD CONSTRAINT CERTIFICATION_HISTORY_FK2 FOREIGN KEY (STAFF_ID) REFERENCES STAFF (STAFF_ID) ON DELETE SET NULL;

  CREATE OR REPLACE FORCE VIEW "BEAM_AUTH_OWNER"."BEAM_DESTINATION_VERIFICATION" ("BEAM_DESTINATION_ID", "VERIFICATION_ID", "EXPIRATION_DATE") AS 
  SELECT a.beam_destination_id, 
  NVL((SELECT MAX(VERIFICATION_ID) FROM control_verification b WHERE a.beam_destination_id = b.beam_destination_id), 1) AS VERIFICATION_ID,
  (SELECT MIN(EXPIRATION_DATE) FROM control_verification b WHERE a.beam_destination_id = b.beam_destination_id) as EXPIRATION_DATE
  FROM hco_owner.beam_destination a;

--Populate Credited Controls
Insert into BEAM_AUTH_OWNER.CREDITED_CONTROL (CREDITED_CONTROL_ID,NAME,DESCRIPTION,GROUP_ID,WEIGHT,VERIFICATION_FREQUENCY) values (13,'Moller Polarimeter Helium and Nitrogen Gas Vent to Hall C','Piping to vent cryogenic gases',7,15,'1 Year');
Insert into BEAM_AUTH_OWNER.CREDITED_CONTROL (CREDITED_CONTROL_ID,NAME,DESCRIPTION,GROUP_ID,WEIGHT,VERIFICATION_FREQUENCY) values (4,'Nitrogen Gas Supply Orifices','1/8" orifice plates to restrict the amount of nitrogen that could be introduced into the tunnel enclosures',11,14,'1 Year');
Insert into BEAM_AUTH_OWNER.CREDITED_CONTROL (CREDITED_CONTROL_ID,NAME,DESCRIPTION,GROUP_ID,WEIGHT,VERIFICATION_FREQUENCY) values (1,'Movable Shielding','Includes penetrations',10,2,null);
Insert into BEAM_AUTH_OWNER.CREDITED_CONTROL (CREDITED_CONTROL_ID,NAME,DESCRIPTION,GROUP_ID,WEIGHT,VERIFICATION_FREQUENCY) values (2,'Permanent Shielding','Includes labyrinths and earth berms',10,1,'5 Years');
Insert into BEAM_AUTH_OWNER.CREDITED_CONTROL (CREDITED_CONTROL_ID,NAME,DESCRIPTION,GROUP_ID,WEIGHT,VERIFICATION_FREQUENCY) values (3,'Beam Dump Cooling Building','Structural integrity of the buildings and their sump pits',9,12,'3 Years');
Insert into BEAM_AUTH_OWNER.CREDITED_CONTROL (CREDITED_CONTROL_ID,NAME,DESCRIPTION,GROUP_ID,WEIGHT,VERIFICATION_FREQUENCY) values (5,'PSS System Level Controls','Principle active engineered safety system that includes PLC circuits and ladder logic',12,3,'8 Months');
Insert into BEAM_AUTH_OWNER.CREDITED_CONTROL (CREDITED_CONTROL_ID,NAME,DESCRIPTION,GROUP_ID,WEIGHT,VERIFICATION_FREQUENCY) values (6,'PSS ODH Monitoring and Alerts','Oxygen sensors and alarms',12,10,'8 Months');
Insert into BEAM_AUTH_OWNER.CREDITED_CONTROL (CREDITED_CONTROL_ID,NAME,DESCRIPTION,GROUP_ID,WEIGHT,VERIFICATION_FREQUENCY) values (7,'PSS Critical Devices','Includes beam stops, beam segment steering electromagnets',12,4,'8 Months');
Insert into BEAM_AUTH_OWNER.CREDITED_CONTROL (CREDITED_CONTROL_ID,NAME,DESCRIPTION,GROUP_ID,WEIGHT,VERIFICATION_FREQUENCY) values (8,'PSS Access Controls','Includes tunnel door maglock, keyswitches',12,5,'8 Months');
Insert into BEAM_AUTH_OWNER.CREDITED_CONTROL (CREDITED_CONTROL_ID,NAME,DESCRIPTION,GROUP_ID,WEIGHT,VERIFICATION_FREQUENCY) values (9,'PSS Sweep Procedures','Includes software and documents',12,6,'8 Months');
Insert into BEAM_AUTH_OWNER.CREDITED_CONTROL (CREDITED_CONTROL_ID,NAME,DESCRIPTION,GROUP_ID,WEIGHT,VERIFICATION_FREQUENCY) values (10,'PSS Interlocks','Includes magnet power supply/RF waveguide pressure interfaces',12,7,'8 Months');
Insert into BEAM_AUTH_OWNER.CREDITED_CONTROL (CREDITED_CONTROL_ID,NAME,DESCRIPTION,GROUP_ID,WEIGHT,VERIFICATION_FREQUENCY) values (11,'PSS Multiple Safety Functions','PSS design implementation of critical safety functions to reduce systematic or common cause failures',12,8,'8 Months');
Insert into BEAM_AUTH_OWNER.CREDITED_CONTROL (CREDITED_CONTROL_ID,NAME,DESCRIPTION,GROUP_ID,WEIGHT,VERIFICATION_FREQUENCY) values (12,'PSS Alarm and Warning Devices','Includes klaxons, beacons',12,9,'8 Months');
Insert into BEAM_AUTH_OWNER.CREDITED_CONTROL (CREDITED_CONTROL_ID,NAME,DESCRIPTION,GROUP_ID,WEIGHT,VERIFICATION_FREQUENCY) values (14,'Locked Doors and Gates','Non-interlocked controls for personnel safety',10,13,null);
Insert into BEAM_AUTH_OWNER.CREDITED_CONTROL (CREDITED_CONTROL_ID,NAME,DESCRIPTION,GROUP_ID,WEIGHT,VERIFICATION_FREQUENCY) values (15,'Permanent Magnet (Tagger)','Magnet to prevent accelerated electrons from entering Hall D',8,11,'1 Year');


--Populate Beam Auth Destinations
insert into beam_auth_destination values(1, 'CEBAF', 'uA', '500 KeV operations', 'Y');
insert into beam_auth_destination values(3, 'CEBAF', 'uA', null, 'Y');
insert into beam_auth_destination values(5, 'CEBAF', 'uA', null, 'Y');
insert into beam_auth_destination values(6, 'CEBAF', 'uA', null, 'Y');
insert into beam_auth_destination values(7, 'CEBAF', 'uA', null, 'Y');
insert into beam_auth_destination values(8, 'CEBAF', 'uA', null, 'Y');
insert into beam_auth_destination values(12, 'CEBAF', 'uA', null, 'Y');

-- Populate Verification
insert into VERIFICATION (VERIFICATION_ID, NAME) values (1, 'Verified');
insert into VERIFICATION (VERIFICATION_ID, NAME) values (50, 'Provisionally Verified');
insert into VERIFICATION (VERIFICATION_ID, NAME) values (100, 'Not Verified');
