DROP SEQUENCE BAM_OWNER.AUTHORIZATION_ID;
DROP SEQUENCE BAM_OWNER.CONTROL_VERIFICATION_ID;
DROP SEQUENCE BAM_OWNER.VERIFICATION_HISTORY_ID;

DROP TABLE BAM_OWNER.VERIFICATION_HISTORY CASCADE CONSTRAINTS PURGE;
DROP TABLE BAM_OWNER.CONTROL_VERIFICATION CASCADE CONSTRAINTS PURGE;
DROP TABLE BAM_OWNER.VERIFICATION CASCADE CONSTRAINTS PURGE;
DROP TABLE BAM_OWNER.CREDITED_CONTROL CASCADE CONSTRAINTS PURGE;
DROP TABLE BAM_OWNER.DESTINATION_AUTHORIZATION CASCADE CONSTRAINTS PURGE;
DROP TABLE BAM_OWNER.AUTHORIZATION CASCADE CONSTRAINTS PURGE;
DROP TABLE BAM_OWNER.BEAM_AUTH_DESTINATION CASCADE CONSTRAINTS PURGE;

CREATE SEQUENCE BAM_OWNER.AUTHORIZATION_ID;
CREATE SEQUENCE BAM_OWNER.CONTROL_VERIFICATION_ID;
CREATE SEQUENCE BAM_OWNER.VERIFICATION_HISTORY_ID;

CREATE TABLE BAM_OWNER.BEAM_AUTH_DESTINATION
(
    BEAM_DESTINATION_ID  INTEGER NOT NULL ,
    MACHINE              VARCHAR2(32 CHAR) DEFAULT  'CEBAF'  NOT NULL ,
    CURRENT_LIMIT_UNITS  VARCHAR2(3 CHAR) DEFAULT  'uA'  NOT NULL ,
    DISPLAY_NAME         VARCHAR2(32 CHAR) NULL ,
    ACTIVE_YN            CHAR(1 BYTE) DEFAULT  'Y'  NOT NULL CONSTRAINT BEAM_AUTH_DESTINATIONS_CK1 CHECK (ACTIVE_YN IN ('Y', 'N')),
    CONSTRAINT BEAM_AUTH_DESTINATIONS_PK PRIMARY KEY (BEAM_DESTINATION_ID)
);

CREATE TABLE BAM_OWNER.AUTHORIZATION
(
    AUTHORIZATION_ID     INTEGER NOT NULL ,
    MODIFIED_DATE        DATE NOT NULL ,
    MODIFIED_BY          INTEGER NOT NULL ,
    AUTHORIZATION_DATE   DATE NOT NULL ,
    AUTHORIZED_BY        INTEGER NOT NULL ,
    COMMENTS             VARCHAR2(2048 CHAR) NULL ,
    CONSTRAINT AUTHORIZATION_PK PRIMARY KEY (AUTHORIZATION_ID)
);

CREATE TABLE BAM_OWNER.DESTINATION_AUTHORIZATION
(
    BEAM_DESTINATION_ID  INTEGER NOT NULL ,
    AUTHORIZATION_ID     INTEGER NOT NULL ,
    BEAM_MODE            VARCHAR2(16) NOT NULL  CONSTRAINT  DESTINATION_AUTHORIZATION_CK1 CHECK (BEAM_MODE IN ('Tune', 'CW', 'None')),
    CW_LIMIT             NUMBER(24,12) NULL ,
    COMMENTS             VARCHAR2(256) NULL ,
    EXPIRATION_DATE      DATE NULL ,
    CONSTRAINT DESTINATION_AUTHORIZATION_PK PRIMARY KEY (BEAM_DESTINATION_ID,AUTHORIZATION_ID),
    CONSTRAINT DESTINATION_AUTHORIZATION_FK1 FOREIGN KEY (AUTHORIZATION_ID) REFERENCES BAM_OWNER.AUTHORIZATION (AUTHORIZATION_ID)
);

CREATE TABLE BAM_OWNER.CREDITED_CONTROL
(
    CREDITED_CONTROL_ID  INTEGER NOT NULL ,
    NAME                 VARCHAR2(128 CHAR) NOT NULL ,
    DESCRIPTION          VARCHAR2(2048 CHAR) NULL ,
    GROUP_ID             INTEGER NOT NULL ,
    WEIGHT               INTEGER NULL ,
    VERIFICATION_FREQUENCY VARCHAR2(128 CHAR) NULL ,
    COMMENTS             VARCHAR2(2048) NULL ,
    CONSTRAINT CREDITED_CONTROL_PK PRIMARY KEY (CREDITED_CONTROL_ID)
);

CREATE TABLE BAM_OWNER.VERIFICATION
(
    VERIFICATION_ID      INTEGER NOT NULL ,
    NAME                 VARCHAR2(128 CHAR) NOT NULL ,
    CONSTRAINT VERIFICATION_PK PRIMARY KEY (VERIFICATION_ID)
);

CREATE TABLE BAM_OWNER.CONTROL_VERIFICATION
(
    CONTROL_VERIFICATION_ID INTEGER NOT NULL ,
    CREDITED_CONTROL_ID  INTEGER NULL ,
    BEAM_DESTINATION_ID  INTEGER NOT NULL ,
    VERIFICATION_ID      INTEGER NOT NULL,
    VERIFICATION_DATE    DATE NULL ,
    VERIFIED_BY          INTEGER NULL ,
    EXPIRATION_DATE      DATE NULL ,
    COMMENTS             VARCHAR2(2048 CHAR) NULL ,
    MODIFIED_BY          INTEGER NOT NULL ,
    MODIFIED_DATE        DATE NOT NULL ,
    CONSTRAINT CONTROL_VERIFICATION_PK PRIMARY KEY (CONTROL_VERIFICATION_ID),CONSTRAINT  CONTROL_VERIFICATION_AK1 UNIQUE (CREDITED_CONTROL_ID,BEAM_DESTINATION_ID),
    CONSTRAINT CONTROL_VERIFICATION_FK1 FOREIGN KEY (CREDITED_CONTROL_ID) REFERENCES BAM_OWNER.CREDITED_CONTROL (CREDITED_CONTROL_ID) ON DELETE CASCADE,
    CONSTRAINT CONTROL_VERIFICATION_FK3 FOREIGN KEY (VERIFICATION_ID) REFERENCES BAM_OWNER.VERIFICATION (VERIFICATION_ID) ON DELETE SET NULL
);

CREATE TABLE BAM_OWNER.VERIFICATION_HISTORY
(
    VERIFICATION_HISTORY_ID INTEGER NOT NULL ,
    CONTROL_VERIFICATION_ID INTEGER NOT NULL ,
    VERIFICATION_ID      INTEGER NOT NULL ,
    VERIFIED_BY          INTEGER NULL ,
    VERIFICATION_DATE    DATE NOT NULL ,
    EXPIRATION_DATE      DATE NULL ,
    COMMENTS             VARCHAR2(2048 CHAR) NULL ,
    MODIFIED_BY          INTEGER NOT NULL ,
    MODIFIED_DATE        DATE NOT NULL ,
    CONSTRAINT VERIFICATION_HISTORY_PK PRIMARY KEY (VERIFICATION_HISTORY_ID),
    CONSTRAINT VERIFICATION_HISTORY_FK1 FOREIGN KEY (CONTROL_VERIFICATION_ID) REFERENCES BAM_OWNER.CONTROL_VERIFICATION (CONTROL_VERIFICATION_ID) ON DELETE CASCADE,
    CONSTRAINT VERIFICATION_HISTORY_FK3 FOREIGN KEY (VERIFICATION_ID) REFERENCES BAM_OWNER.VERIFICATION (VERIFICATION_ID) ON DELETE SET NULL
);

--ALTER TABLE CONTROL_VERIFICATION ADD CONSTRAINT CONTROL_VERIFICATION_FK2 FOREIGN KEY (BEAM_DESTINATION_ID) REFERENCES hco_owner.BEAM_DESTINATION (BEAM_DESTINATION_ID) ON DELETE SET NULL;

--ALTER TABLE CREDITED_CONTROL ADD CONSTRAINT CREDITED_CONTROL_FK1 FOREIGN KEY (WORKGROUP_ID) REFERENCES WORKGROUP (WORKGROUP_ID) ON DELETE SET NULL;

--ALTER TABLE DESTINATION_AUTHORIZATION ADD CONSTRAINT DESTINATION_AUTHORIZATION_FK2 FOREIGN KEY (BEAM_DESTINATION_ID) REFERENCES hco_owner.BEAM_DESTINATION (BEAM_DESTINATION_ID) ON DELETE SET NULL;

--ALTER TABLE CREDITED_CONTROL ADD CONSTRAINT CREDITED_CONTROL_FK3 FOREIGN KEY (STAFF_ID) REFERENCES STAFF (STAFF_ID) ON DELETE SET NULL;

--ALTER TABLE CERTIFICATION_HISTORY ADD CONSTRAINT CERTIFICATION_HISTORY_FK2 FOREIGN KEY (STAFF_ID) REFERENCES STAFF (STAFF_ID) ON DELETE SET NULL;

--CREATE OR REPLACE FORCE VIEW BAM_OWNER.BEAM_DESTINATION_VERIFICATION ("BEAM_DESTINATION_ID", "VERIFICATION_ID", "EXPIRATION_DATE") AS
--SELECT a.beam_destination_id,
--      NVL((SELECT MAX(VERIFICATION_ID) FROM control_verification b WHERE a.beam_destination_id = b.beam_destination_id), 1) AS VERIFICATION_ID,
--       (SELECT MIN(EXPIRATION_DATE) FROM control_verification b WHERE a.beam_destination_id = b.beam_destination_id) as EXPIRATION_DATE
--FROM hco_owner.beam_destination a;